---
title: "Hypothesis Testing"
format: html
editor: visual
---

```{r}
# Extract the estimated parameters
estimated_params <- coef(result)

# Calculate the z-value
z_value <- (estimated_params[2] - 0.5) / standard_errors[2]

# Calculate the two-tailed p-value
p_value <- 2 * pnorm(-abs(z_value))

# Set the significance level (e.g., 0.05)
alpha <- 0.05

# Compare p-value to the significance level
if (p_value < alpha) {
  cat("Reject the null hypothesis. There is evidence that the bias for aces in the next point, given the previous point was an ace, is different from 0.5.")
} else {
  cat("Fail to reject the null hypothesis. There is not enough evidence to suggest a difference in the bias for aces in the next point, given the previous point was an ace.")
}

# Print z-value and p-value
cat("\nZ-value:", z_value, "\nP-value:", p_value)

```

```{r}

# Ho: there is a significant difference between the two models
# Ha: there is no significant difference in the two models

# Hypothesis testing between the models
loglik0 <- -35979.94
loglik1 <- -80497.31

# Calculate the likelihood ratio statistic
likelihood_ratio_stat <- -2 * (loglik0 - loglik1)


df <- 0

# Calculate the p-value using the chi-square distribution
p_value <- pchisq(likelihood_ratio_stat, df, lower.tail = FALSE)

x <- 0.05


if (p_value < x) {
  cat("Reject the null hypothesis. There is a significant difference between the two models.\n")
} else {
  cat("Fail to reject the null hypothesis. There is no significant difference between the two models.\n")
}

```

Neither the ace or error model is significantly better than the other.

```{r}
loglik <- as.double(80497)
lr_test <- -2 * sum(loglik - logLik(null_model))  # Likelihood ratio statistic
df <- length(mles)  # Degrees of freedom
p_value <- pchisq(lr_test, df, lower.tail = FALSE)
```

```{r}
# summary(mod4) |> names() # check names in summary object

ts_lof <- summary(mod4)$deviance # lack of fit test statistic
df_lof <- summary(mod4)$df.residual # df lack of fit test 

pval_lof <- pchisq(ts_lof, df_lof, lower.tail = FALSE)

pval_lof
```
